version: 2
storybook:
  waitForTimeout: 3000
snapshot:
  enable-javascript: true
discovery:
  user-agent: "percy-backpack"
  allowed-hostnames:
    - content.skyscnr.com
  launch-options:
    timeout: 9000
